routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@main')->name('main.home');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('articles', 'ArticlesController', ['except' => ['show']]);
    Route::get('articles/{id}/setting', 'ArticlesController@setting')->name('articles.setting');
    Route::resource('users', 'UsersController');
});

Route::get('articles/{id}', 'ArticlesController@show')->name('articles.show');

app/Article.php
<?php

namespace App;

use App\User;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Article extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'body', 'user_id', 'make_public'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\ArticleContract;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;


class ArticlesController extends Controller
{
    protected $articlesRepo;

    public function __construct(ArticleContract $articlesContract)
    {
        $this->articlesRepo = $articlesContract;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $articles = $user->articles;
        return view('articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'body' => 'required'
        ]);


        $request = $request->except(['_token', '_method', 'files']);

        $params = [
            'title' => $request['title'],
            'body' => $request['body'],
            'user_id' => Auth::id()
        ];

        $article = $this->articlesRepo->create($params);

        Session::flash('flash_message', 'Article successfully created');
        return redirect()->route('articles.show', $article->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = $this->articlesRepo->show($id);
        if (is_null($article)) {
            abort(404);
        }

        if ($article->make_public) {
            return view('articles.show', compact('article'));
        } elseif (Auth::check() && $article->user_id == Auth::User()->id) {
            return view('articles.show', compact('article'));
        } else {
            abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = $this->articlesRepo->show($id);

        if ($article->user_id == Auth::User()->id) {
            return view('articles.edit', compact('article'));
        } else {
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request = $request->except(['_token', '_method', 'files']);

        $this->articlesRepo->update($id, $request);
        $article = $this->articlesRepo->show($id);

        Session::flash('flash_message', 'Article successfully updated');
        return redirect()->route('articles.show', $article->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->articlesRepo->delete($id);
        Session::flash('flash_message', 'Article successfully deleted');

        return redirect()->back();
    }

    public function setting($id)
    {
        $article = $this->articlesRepo->show($id);
        if ($article->user_id == Auth::User()->id) {
            return view('articles.setting', compact('article'));
        } else {
            abort(404);
        }
    }
}

app/Http/Controllers/Test/ArticlesController.php
<?php

namespace App\Http\Controllers\Test;

use App\Article;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $articles = $user->articles;
        return response()->json($articles, 201);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'body' => 'required'
        ]);

        $input = $request->all();
        //For Test Case
        $article = Article::create($input);
        return response()->json($article, 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id);
        if($article->make_public || $article->user_id == Auth::User()->id)
        {
            return response()->json($article, 201);
        } else {
            abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        if ($article->user_id == Auth::User()->id) {
            return response()->json($article, 201);
        } else {
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
        ]);

        $input = $request->all();
        $article = Article::find($id);
        $article->update($input);
        return response()->json($article, 201);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
        $article->delete();
        Session::flash('flash_message', 'Article successfully deleted');
        return redirect()->back();
    }

    public function setting($id)
    {
        $article = Article::find($id);
        if ($article->user_id == Auth::User()->id) {
            return response()->json($article, 201);

        } else {
            abort(404);
        }
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('partials._error')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create new Article</div>
                <div class="panel-body">
                    <form method="POST" action="{{ route('articles.store') }}" novalidate>
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="title">Title (Optional)</label>
                            <input type="text" class="form-control" id="title" name="title">
                        </div>
                        <div class="form-group">
                            <label for="body">Body</label>
                            <textarea required class="form-control summernote" id="body" name="body"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('partials._error')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit {{ $article->title }}</div>
                <div class="panel-body">
                    <form method="POST" action="{{ route('articles.update', $article->id) }}" novalidate>
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="title">Title (Optional)</label>
                            <input type="text" class="form-control" id="title" name="title" value="{{ $article->title }}">
                        </div>
                        <div class="form-group">
                            <label for="body">Body</label>
                            <textarea name="body" required class="form-control summernote" id="body">{{ $article->body }}</textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('partials._flash')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Articles
                    <a class="pull-right btn btn-success btn-xs" href="{{ route('articles.create') }}">+ New Article</a>
                </div>
                <div class="panel-body">
                    @if($articles->count())
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Created At</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($articles as $article)
                                    <tr class='clickable-row' data-href='{{route('articles.show', $article->id)}}'>
                                        <td>
                                            {{ $article->title }}
                                        </td>
                                        <td>{{ $article->created_at->format('l jS \\of F Y') }}</td>
                                        <td>
                                            <form method="POST" action="{{ route('articles.destroy', $article->id) }}" accept-charset="UTF-8" class="form-inline pull-right">
                                                {{ method_field('DELETE') }}
                                                {{csrf_field()}}
                                                <button type="submit" class="btn btn-xs btn-danger confirm-delete"><i class="fa fa-trash-o"></i> Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    @else
                        No Articles Found
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        jQuery(document).ready(function($) {
            $(".clickable-row").click(function() {
                window.location = $(this).data("href");
            });
        });
    </script>
@endsection

resources/views/articles/setting.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @include('partials._error')
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Setting {{ $article->title }}</div>
                    <div class="panel-body">
                        <form method="POST" action="{{ route('articles.update', $article->id) }}" novalidate>
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="form-group">
                                <label for="title">Make Public (Optional)</label>
                                <select name="make_public" id="" class="form-control">
                                    <option value="0" {{$article->make_public == 0? 'selected': ''}} >No</option>
                                    <option value="1" {{$article->make_public == 1? 'selected': ''}} >Yes</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('styles')
    <style>
        .panel-body > p > img {
            max-width: 100%;
        }
    </style>
@endsection
@section('content')
<div class="container">
    @include('partials._flash')
    <div class="row">
        <div class="col-md-12 col-lg-12">
            @if(!Auth::guest())
                <a href="{{ route('articles.index') }}" class="btn btn-primary btn-xs custom-btn"><i class="fa fa-angle-left" aria-hidden="true"></i> Back</a>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span>
                         <strong>{!! $article->title?$article->title:'&nbsp'!!}</strong>
                    </span>
                        @if(!Auth::guest() && Auth::User()->id == $article->user_id)
                        <span class="pull-right">
                        <a href="{{ route('articles.edit', $article->id) }}" class="btn btn-primary btn-xs"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</a>
                        <a href="{{ route('articles.setting', $article->id) }}"  class="btn btn-primary btn-xs"><i class="fa fa-cog" aria-hidden="true"></i> Settings</a>
                        </span>
                        @endif

                </div>
                <div class="panel-body">
                    {!! $article->body !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection